### PR TITLE
Replace klog with zerolog in Lighthouse Agent

### PR DESCRIPTION
**Pull request by tpantelis**
Using the `kzerolog` package from [admiral](https://github.com/submariner-io/admiral/tree/devel/pkg/log/kzerolog). 

**Note**: some internal k8s packages uses `klog` directly, so few logs may still be printed in the `klog` format.

**Note**: this was originally submitted with https://github.com/submariner-io/lighthouse/pull/692 however the original author left the project.

Signed-off-by: David Ohana <david.ohana@ibm.com>

### CODE REVIEW

**Comment by tpantelis** [comment]
This is a little more complicated. Now that K8s was bumped to v1.21, `kzerolog` in **admiral** needs to updated to use [logr 1.2.0](https://github.com/submariner-io/admiral/pull/342).

**Comment by vthapar** [comment]
@tpantelis Do we need a fresh PR for this after 1.21 changes?

**Comment by tpantelis** [comment]
> @tpantelis Do we need a fresh PR for this after 1.21 changes?

This is a new PR. We need https://github.com/submariner-io/admiral/pull/342.

**Comment by dfarrell07** [comment]
I think this was blocked on a K8s version bump? We now have 1.24, can we revisit this?

**Comment by skitt** [comment]
> I think this was blocked on a K8s version bump? We now have 1.24, can we revisit this?

We don’t have 1.24 yet, see https://github.com/submariner-io/shipyard/pull/825

**Comment by dfarrell07** [comment]
> > I think this was blocked on a K8s version bump? We now have 1.24, can we revisit this?
> 
> We don’t have 1.24 yet, see [submariner-io/shipyard#825](https://github.com/submariner-io/shipyard/pull/825)

Ah thanks, getting ahead of myself.

**Review by dfarrell07 — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
@tpantelis this needs a manual rebase.

**Pull request merged**
