### PR TITLE
Unpin Kubernetes dependencies

### PR DESCRIPTION
**Pull request by skitt**
This doesn't seem to break anything, and helps with go install (see
<https://github.com/golang/go/issues/44840>).

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
The issues with the various unpin K8s patches are that the bump to 0.20 ends up breaking Admiral, because of changes in the fake client which result in errors handling List objects.

**Review by dfarrell07 — APPROVED** [review]

**Review by aswinsuryan — APPROVED** [review]

**Comment by dfarrell07** [comment]
When we get this working, we should also consider enabling the `gomoddirectives` linter to keep replace statements out.

https://github.com/submariner-io/lighthouse/blob/devel/.golangci.yml#L61

**Comment by nyechiel** [comment]
@skitt I assume we want this fixed for 0.12?

**Comment by skitt** [comment]
> @skitt I assume we want this fixed for 0.12?

I would have liked it fixed for 0.12, but it’s too complex! We’ll have to punt it to 0.13.

**Comment by skitt** [comment]
The build is now broken because our Kubernetes dependencies require Go 1.17.

**Comment by tpantelis** [comment]
Done with https://github.com/submariner-io/lighthouse/pull/744.

**Pull request closed without merging**
