### PR TITLE
Fix Markdown linting errors

### PR DESCRIPTION
**Pull request by dfarrell07**
Will be tested by the verify job once it's update in Shipyard.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
> While it's nice to have as GHA, wouldn't it be better if we incorporate it into Shipyard's basic validate.sh script?

Excellent point, it would definitely be better if all validations can also run locally.

**Comment by dfarrell07** [comment]
> > While it's nice to have as GHA, wouldn't it be better if we incorporate it into Shipyard's basic validate.sh script?
> 
> Excellent point, it would definitely be better if all validations can also run locally.

I asked that on my first MD lint PR. :sweat_smile: 

https://github.com/submariner-io/submariner-website/pull/214#issuecomment-666605187

**Comment by dfarrell07** [comment]
> > > While it's nice to have as GHA, wouldn't it be better if we incorporate it into Shipyard's basic validate.sh script?
> > 
> > 
> > Excellent point, it would definitely be better if all validations can also run locally.
> 
> I asked that on my first MD lint PR. 
> 
> [submariner-io/submariner-website#214 (comment)](https://github.com/submariner-io/submariner-website/pull/214#issuecomment-666605187)

We can do it in the normal way for most repos (adding to the verify script), but we don't have that infra in the website repo.

**Comment by mkolesnik** [comment]
> > I asked that on my first MD lint PR.
> > [submariner-io/submariner-website#214 (comment)](https://github.com/submariner-io/submariner-website/pull/214#issuecomment-666605187)
> 
> We can do it in the normal way for most repos (adding to the verify script), but we don't have that infra in the website repo.

Yes I think that way would be better and leave the GHA on the website.

**Comment by dfarrell07** [comment]
> > > I asked that on my first MD lint PR.
> > > [submariner-io/submariner-website#214 (comment)](https://github.com/submariner-io/submariner-website/pull/214#issuecomment-666605187)
> > 
> > 
> > We can do it in the normal way for most repos (adding to the verify script), but we don't have that infra in the website repo.
> 
> Yes I think that way would be better and leave the GHA on the website.

Perfect, that's easy then. Thanks! :+1:

**Pull request merged**
