### PR TITLE
Add K8s 1.24 E2E, EoL K8s 1.21

### PR DESCRIPTION
**Pull request by dfarrell07**
Use Kubernetes 1.24 as the default version for end-to-end tests.

Remove Kubernetes 1.21 end-to-end tests as it's end of life.

Depends on https://github.com/submariner-io/submariner-charts/pull/235
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
The 1.24 jobs seem to consistently time out.

**Comment by tpantelis** [comment]
> The 1.24 jobs seem to consistently time out.

yeah - perhaps we should temporarily bump the timeout much higher in this PR (like 2 hours) in hopes the tests will complete with actionable errors.

**Comment by tpantelis** [comment]
In [this job run](https://github.com/submariner-io/lighthouse/runs/7396692942?check_suite_focus=true), the test cases succeed up to a point where it fails with a "client connection lost" accessing the kube API server after which all tests fail with "tcp 172.18.0.4:6443: connect: connection refused" errors.  So at some point, strangely the API server (I think on cluster1) becomes unavailable. Also strange is that **Post Mortem** section is missing the log.

[This job](https://github.com/submariner-io/lighthouse/runs/7396693088?check_suite_focus=true) fails after 44m but with no logs at all.

**Comment by dfarrell07** [comment]
Talked about this on the Scrub, we think the issue is that this repo LH tests deploy three clusters and it runs out of resources. Need to figure out how to use fewer resources.

**Comment by mkolesnik** [comment]
> Talked about this on the Scrub, we think the issue is that this repo LH tests deploy three clusters and it runs out of resources. Need to figure out how to use fewer resources.

I've tested locally (1.24) and found that minimal clusters work perfectly fine, hopefully it'll help the CI here #828

**Comment by mkolesnik** [comment]
Both `globalnet` jobs are now failing on one test:
```
[Fail] [discovery] Test Headless Service Discovery Across Clusters when the number of active pods backing a service changes [It] should resolve the local pod IPs 
```

**Comment by tpantelis** [comment]
> Both `globalnet` jobs are now failing on one test:
> 

Making progress tho!! @aswinsuryan any ideas on the [failure](https://github.com/submariner-io/lighthouse/runs/7428265270?check_suite_focus=true)?

**Comment by mkolesnik** [comment]
Helm deployment seems to be broken globally now

**Comment by dfarrell07** [comment]
> End to End Full / E2E (operator, globalnet, 1.24) (pull_request) 

Not only Helm is bonked.

**Comment by aswinsuryan** [comment]
> > Both `globalnet` jobs are now failing on one test:
> 
> Making progress tho!! @aswinsuryan any ideas on the [failure](https://github.com/submariner-io/lighthouse/runs/7428265270?check_suite_focus=true)?

This PR is working fine when tested locally. I was not able to reproduce it after multiple retries.

**Comment by tpantelis** [comment]
> This PR is working fine when tested locally. I was not able to reproduce it after multiple retries.

Are you using K8s 1.24?

**Pull request merged**
