### PR TITLE
Run SonarScan, publish unit results and coverage

### PR DESCRIPTION
**Pull request by dfarrell07**
Run SonarScan checks on merges.

Publish Go unit test results and coverage profile to SonarCloud.

Add a Sonar config file describing the project and unit test results.

Also limit all reporting to non-fork repos.

This may need to be split into multiple jobs that upload/download
artifacts once we start publishing golangci-lint results to SonarCloud
per submariner-io/shipyard#868. For now want to test incrementally.

Relates-to: stolostron/backlog#22706
Relates-to: submariner-io/shipyard#869
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
It wasn’t immediately obvious to me, so I’ll mention it here in case it helps others: as mentioned in the description, this runs on merges, not on PRs generally, so it’s not causing a double execution of unit tests (with `.github/workflows/unit.yml`) on PRs.

**Review by nyechiel — APPROVED** [review]

**Comment by dfarrell07** [comment]
> 16:36:41.188 INFO: Check ALM binding of project 'submariner-io_lighthouse'
16:36:41.318 DEBUG: GET 404 https://sonarcloud.io/api/alm_integration/is_project_bound?project=submariner-io_lighthouse | time=130ms
16:36:41.319 INFO: Detected project binding: NONEXISTENT
16:36:41.319 INFO: Check ALM binding of project 'submariner-io_lighthouse' (done) | time=131ms

I think we need to do something on the SonarCloud side to create/link the project? https://community.sonarsource.com/t/new-sonarcloud-scans-failing-all-of-a-sudden/26899/18

**Comment by dfarrell07** [comment]
I think we need an admin (SonarCloud auth is 1:1 with GH auth) to add Lighthouse (and others maybe while we're at it) as a Project here: https://sonarcloud.io/projects/create

**Comment by dfarrell07** [comment]
And with help from Tom it's working :partying_face: https://sonarcloud.io/project/overview?id=submariner-io_lighthouse

**Pull request merged**
