### PR TITLE
Update to latest shipyard/admiral versions

### PR DESCRIPTION
**Pull request by Jaanki**
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Comment by mangelajo** [comment]
Oh, lighthouse got never pinned to 0.9.0?

**Comment by mangelajo** [comment]
Do you need those specific versions for some reason now?

Stable branch is correctly pinned to v0.9.0 
https://github.com/submariner-io/lighthouse/blob/release-0.9/go.mod#L19

**Comment by Jaanki** [comment]
devel should be pinned to latest version right. So the new work is on top of 0.9.0.

**Comment by mangelajo** [comment]
> devel should be pinned to latest version right. So the new work is on top of 0.9.0.

There is no harm in doing so, not sure if there are really changes , may be in shipyard, I'm fine with it ;)

**Review by mangelajo — APPROVED** [review]

**Review by mkolesnik — CHANGES_REQUESTED** [review]
> devel should be pinned to latest version right. So the new work is on top of 0.9.0.

devel should be *updated* to devel so please update to the latest devel versions

also this isn't *pinning* it's just version bumps for go dependencies which are internal

**Comment by mangelajo** [comment]
Yeah, mike has a point. 

I mean, we don't really need the change of pinning for any specific reason, but if we do it, let's do it to the current devel :)

**Review by mangelajo — CHANGES_REQUESTED** [review]
see last comments

**Review by mkolesnik — CHANGES_REQUESTED** [review]
You need to run `go mod tidy` there are some uncommitted changes there

**Comment by tpantelis** [comment]
This is superseded by https://github.com/submariner-io/lighthouse/pull/528.

**Pull request closed without merging**
