### PR TITLE
Update grpc to fix CVEs

### PR DESCRIPTION
**Pull request by dfarrell07**
Update generated by `go get -u google.golang.org/grpc`/`go mod tidy`.

Fixes GHSA-m425-mq94-257g and GHSA-qppj-fm5r-hxr3.

### CODE REVIEW

**Comment by dfarrell07** [comment]
`go mod tidy` undoes the update...

**Comment by dfarrell07** [comment]
Oh it's in the coredns submodule, that must be why. Trying again.

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
[E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18448016934?pr=1434#logs) failed, re-running.

**Comment by dfarrell07** [comment]
> [E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18448016934?pr=1434#logs) failed, re-running.

[E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18449384127?pr=1434#logs) failed again.

**Comment by tpantelis** [comment]
> [E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18449384127?pr=1434#logs) failed again.

It panics due to the shipyard issue.  Need to bump shipyard version as well.

**Comment by dfarrell07** [comment]
> > [E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18448016934?pr=1434#logs) failed, re-running.
> 
> [E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18449384127?pr=1434#logs) failed again.

It looks like it was failing yesterday too and we merged over it. https://github.com/submariner-io/lighthouse/pull/1433

**Comment by dfarrell07** [comment]
> > [E2E (operator, globalnet, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/6786758153/job/18449384127?pr=1434#logs) failed again.
> 
> It panics due to the shipyard issue. Need to bump shipyard version as well.

Added a Shipyard bump commit :crossed_fingers:

**Review by aswinsuryan — APPROVED** [review]

**Pull request merged**
