### PR TITLE
Use latest `Shipyard` for simpleserver

### PR DESCRIPTION
**Pull request by mkolesnik**
Shipyard's E2E framework was updated to use a simple server, the
consuming projects need to update in order to properly consume it.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
The E2E default tests timed out, re-running.

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
Upgrade failed, various E2E timed out.

**Comment by dfarrell07** [comment]
I think the E2E is "timing out" when it's actually failing, because it does more redeploys/retries and then times out in the post mortem. I sent a PR to fix this: https://github.com/submariner-io/lighthouse/pull/736

**Comment by dfarrell07** [comment]
It makes sense that the upgrade job is failing, see https://github.com/submariner-io/lighthouse/pull/736#issuecomment-1111213026.

**Comment by dfarrell07** [comment]
E2E seems like it's passing `make deploy` and the connection test, and then failing the actual E2E tests.

We still have old-style nginx stuff here: https://github.com/submariner-io/lighthouse/pull/730/files#diff-c354587e36151f73f4a4da62c22d612510bee633ada8a52ed16b89c7185f0283

Any ideas @vthapar @aswinsuryan?

**Comment by dfarrell07** [comment]
Testing a fix here: https://github.com/submariner-io/lighthouse/pull/737

**Comment by mkolesnik** [comment]
I have a fix here - https://github.com/submariner-io/lighthouse/pull/738

**Comment by mkolesnik** [comment]
Solved by #738

**Pull request closed without merging**
