### PR TITLE
Fix version script

### PR DESCRIPTION
**Pull request by mkolesnik**
Copied over the script from submariner for calculating the image version

### CODE REVIEW

**Comment by skitt** [comment]
Wouldn’t this be better as a shared script in Shipyard?

**Comment by aswinsuryan** [comment]
> Wouldn’t this be better as a shared script in Shipyard?

raised an issue to keep track of it. https://github.com/submariner-io/shipyard/issues/144

**Comment by mkolesnik** [comment]
> Wouldn’t this be better as a shared script in Shipyard?

It's already a shared script, theres also issues open to adopt more parts of shipyard (which use this script)

**Comment by skitt** [comment]
> > Wouldn’t this be better as a shared script in Shipyard?
> 
> It's already a shared script, theres also issues open to adopt more parts of shipyard (which use this script)

Indeed; the fact that this updates the copied file made me think it wasn’t.

**Comment by mkolesnik** [comment]
> 
> Indeed; the fact that this updates the copied file made me think it wasn’t.

It was a stop gap solution, I'm working on adapting the Shipyard stuff now

**Pull request merged**
