### PR TITLE
Add CI badges to README

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
These link check failures don't make sense, it passes locally for me and the links work in the browser.

```
ERROR: 3 dead links found!
[✖] https://github.com/submariner-io/lighthouse/workflows/End%20to%20End%20Tests/badge.svg → Status: 404
[✖] https://github.com/submariner-io/lighthouse/workflows/Unit%20Tests/badge.svg → Status: 404
[✖] https://github.com/submariner-io/lighthouse/workflows/Release%20Images/badge.svg → Status: 404
```

**Comment by tpantelis** [comment]
> These link check failures don't make sense, it passes locally for me and the links work in the browser.
> 
> ```
> ERROR: 3 dead links found!
> [✖] https://github.com/submariner-io/lighthouse/workflows/End%20to%20End%20Tests/badge.svg → Status: 404
> [✖] https://github.com/submariner-io/lighthouse/workflows/Unit%20Tests/badge.svg → Status: 404
> [✖] https://github.com/submariner-io/lighthouse/workflows/Release%20Images/badge.svg → Status: 404
> ```

yeah looks similar to the false alarms reported in https://github.com/submariner-io/submariner-operator/issues/959.

**Comment by dfarrell07** [comment]
> > These link check failures don't make sense, it passes locally for me and the links work in the browser.
> > ```
> > ERROR: 3 dead links found!
> > [✖] https://github.com/submariner-io/lighthouse/workflows/End%20to%20End%20Tests/badge.svg → Status: 404
> > [✖] https://github.com/submariner-io/lighthouse/workflows/Unit%20Tests/badge.svg → Status: 404
> > [✖] https://github.com/submariner-io/lighthouse/workflows/Release%20Images/badge.svg → Status: 404
> > ```
> 
> yeah looks similar to the false alarms reported in [submariner-io/submariner-operator#959](https://github.com/submariner-io/submariner-operator/issues/959).

So weird. I guess I can add them to the ignore config.

https://github.com/submariner-io/lighthouse/blob/master/.markdownlinkcheck.json

**Comment by dfarrell07** [comment]
Based on https://github.com/submariner-io/lighthouse/pull/402 to fix the real links failues and added a commit to ignore the badge false falures.

**Review by tpantelis — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Pull request merged**
