### PR TITLE
Add periodic E2E tests to find flaky failures

### PR DESCRIPTION
**Pull request by dfarrell07**
See commit messages for details.

### CODE REVIEW

**Comment by dfarrell07** [comment]
@skitt @tpantelis @mkolesnik @mangelajo Thinking about this more, does it actually make sense to have these periodic E2E tests on repos other than submariner-io/submariner? Doesn't this run a subset of the same deployments/tests? Having the periodic E2E tests on only one repo would make it easier to tweak the timing and would centralize the data stream.

**Comment by tpantelis** [comment]
> @skitt @tpantelis @mkolesnik @mangelajo Thinking about this more, does it actually make sense to have these periodic E2E tests on repos other than submariner-io/submariner? Doesn't this run a subset of the same deployments/tests? Having the periodic E2E tests on only one repo would make it easier to tweak the timing and would centralize the data stream.

The repos run different tests specific to their functionality.  Perhaps we can run the periodic job in shipyard similar to job that runs e2e on all consuming projects triggered by the PR label.

**Comment by dfarrell07** [comment]
> > @skitt @tpantelis @mkolesnik @mangelajo Thinking about this more, does it actually make sense to have these periodic E2E tests on repos other than submariner-io/submariner? Doesn't this run a subset of the same deployments/tests? Having the periodic E2E tests on only one repo would make it easier to tweak the timing and would centralize the data stream.
> 
> The repos run different tests specific to their functionality. Perhaps we can run the periodic job in shipyard similar to job that runs e2e on all consuming projects triggered by the PR label.

Okay, good idea. I sent a PR to Shipyard: https://github.com/submariner-io/shipyard/pull/358

**Comment by dfarrell07** [comment]
Working through implementing this in Shipyard, I'm starting to think it's better to use this per-repo design.

1. To make the build matrix exactly match the matrixes of the consuming projects, we need a complex set of excludes that will be difficult to maintain.
2. With a more minimal set of excludes, we run 60+ jobs.
3. It's easier to maintain the test matrixes in each project by just making sure the same `using` flags are in the Periodic E2E and E2E workflows, vs keeping the Shipyard matrix up-to-date and having to think about all the projects.
4. To get better observability using per-project tests, we can add GHA step to report an issue on failures. That would be a middle ground between a very easy to see single workflow and this design.

**Comment by dfarrell07** [comment]
Closing in favor of https://github.com/submariner-io/submariner-operator/pull/786.

**Pull request closed without merging**
